### PR TITLE
Create KNES_IVA.cfg

### PR DESCRIPTION
**Pull request by AtomikkuSan**
Uses KNES' IVA database.
Please don't merge until this pull request is accepted. https://github.com/AstroWell/Knes/pull/33
Personal favor, could you ask Well to take a look into this pull request?

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
That PR (Knes#33) may be a while.
I'll ask him, not holding my breath

**Comment by AtomikkuSan** [comment]
thanks :)

**Comment by AtomikkuSan** [comment]
@linuxgurugamer, you can release the current updates and the KNES one later :)

**Comment by linuxgurugamer** [comment]
Hi, I just merged all your patches, I'm g reverting this commit, once I release the current, you can resubmit the PR

**Pull request merged**
