### PR TITLE
Create CONFIG_X-37B_crewModule.cfg

### PR DESCRIPTION
**Pull request by AtomikkuSan**

### CODE REVIEW

**Comment by AtomikkuSan** [comment]
I'd really like to find someone who'd be willing to make an IVA for this.

**Comment by linuxgurugamer** [comment]
Thanks, I'm going to wait until Sunday to merge all of these, only want to do one release.

**Comment by AtomikkuSan** [comment]
Gotcha, thanks!

**Comment by AtomikkuSan** [comment]
And don't DM me on the forums for the next few weeks, it'd be greatly appreciated.

**Comment by AtomikkuSan** [comment]
Also, just write my username and not ping me, It'd also be greatly appreciated.

**Pull request merged**
